add_subdirectory(system_info)
add_subdirectory(process_demo)
add_subdirectory(process_fork_demo)
add_subdirectory(process_exec_demo)
add_subdirectory(process_wait_demo)
add_subdirectory(process_zombie_demo)
add_subdirectory(process_signal_demo)
add_subdirectory(process_orphan_demo)
add_subdirectory(thread_create_demo)
add_subdirectory(race_condition_demo)
add_subdirectory(mutex_counter_demo)
add_subdirectory(thread_memory_demo)
add_subdirectory(condition_variable_demo)
